version: '3'
services:
  flask-atlantis:
    container_name: flask-atlantis
    restart: always
    env_file: .env
    build: .
    ports:
      - "5085:5005"
    networks:
      - net-front

networks:
  net-front:
    driver: bridge
 